---
all:
  children:
    mx:
      children:
        mx-staging:
          hosts:
            staging.vientos.coop:
              ansible_host: 136.243.86.184
              ansible_port: 2222
              ansible_python_interpreter: /usr/bin/python3
