---
 - name: Check if certificate already exists
   stat:
     path: "/etc/letsencrypt/live/{{ domain }}/cert.pem"
   register: live_cert

 - name: Generate new certificate if one doesn't exist
   shell: "certbot certonly --nginx --non-interactive --agree-tos --email {{ secrets.common.letsencryptEmail }} -d {{ domain }} {% if alternative_domain is defined %} -d {{ alternative_domain }} {% endif %} {% if letsencrypt_staging %} --staging {% endif %}"
   when: not live_cert.stat.exists