---
 - name: Check if certificate already exists
   stat:
     path: "/etc/letsencrypt/live/{{ domain }}/cert.pem"
   register: live_cert

 - name: Generate new certificate if one doesn't exist
   shell: "certbot certonly --nginx --email {{ secrets.common.letsencryptEmail }} --agree-tos -d {{ domain }} {% if letsencrypt_staging %} --staging {% endif %}"
   when: not live_cert.stat.exists